### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by Udayraj123** [uselotus/typescript-sdk#19]
I was referring to [this documentation](https://docs.uselotus.io/api-reference/events/tracking) to test out the lotus typescript package on a self hosted version. But I encountered the following error:

Stack Trace:
```
index.js:18 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at isApiError (index.js:18:1)
    at callReq (index.js:32:1)
    at Lotus.flush (index.js:150:1)
    at index.js:123:1
isApiError	@	index.js:18
callReq	@	index.js:32
flush	@	index.js:150
(anonymous)	@	index.js:123
setTimeout (async)		
enqueue	@	index.js:123
trackEvent	@	index.js:167
onClick	@	index.js:45
handleClick	@	button.js:124
callCallback	@	react-dom.development.js:4164
invokeGuardedCallbackDev	@	react-dom.development.js:4213
invokeGuardedCallback	@	react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError	@	react-dom.development.js:4291
executeDispatch	@	react-dom.development.js:9041
processDispatchQueueItemsInOrder	@	react-dom.development.js:9073
processDispatchQueue	@	react-dom.development.js:9086
dispatchEventsForPlugins	@	react-dom.development.js:9097
(anonymous)	@	react-dom.development.js:9288
batchedUpdates$1	@	react-dom.development.js:26140
batchedUpdates	@	react-dom.development.js:3991
dispatchEventForPluginEventSystem	@	react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay	@	react-dom.development.js:6465
dispatchEvent	@	react-dom.development.js:6457
dispatchDiscreteEvent
```

The debug point in the source code:
<img width="425" alt="image" src="https://user-images.githubusercontent.com/16881051/226861255-9c0188cb-6681-40bc-9293-9896bb0b3abb.png">

Steps to reproduce: 
- Simply called lotus.trackEvent() with `http://localhost` as the host name

Any help is appreciated!

**Comment by mnida** [comment]
Hey @Udayraj123 .  First can you make sure you are on 1.2.7 for this SDK and on the most recent main branch for Lotus.

Can you send the code you used for your lotus.trackEvent() call?

You need to do something like this, which should be specified in the docs.

```
const { Lotus } = require("lotus-typescript");

const lotus = new Lotus(API_KEY, {
  host: "http://localhost",
});

function trackMessage() {
  lotus.trackEvent({
    event_name: "message",
    properties: {
      messageCount: 231,
    },
    customer_id: "customer123",
  });

}

```

**Comment by mnida** [comment]
Please double check that you pulled 0.10.2 from lotus as well

**Comment by Udayraj123** [comment]
Hi @mnida,  
If I recall correctly  I had pasted this code from the docs -
```
lotus.trackEvent({
  event_name: "test", // required
  time_created: new Date(), // optional, if not provided current time will be taken
  customer_id: "cust_5894767364aa4e64", // required
  properties: { test: "test", numericQuantity: 3.1415 }, //optional, pass in any additional properties you want to aggregate or measure
  idempotency_id: "c2c5eb5d-de4b-44e0", //optional if not provided Randomly generated ID will be taken
});
```
I see I might have used the current released version on github i.e. 1.0.29 thus causing above problem.

Yet, I may not find the time to test this again soon (code changed to try another tool). Please feel free to close the issue if it'd get stale.
